#!/usr/bin/python3
#Name:zhangjun
#Email:aceg452161724@qq.com
#Time:2017/10/20 16:35

import getpass  #getpass 标准库

username = input("uername:")
password = input(getpass.getpass("password:"))

print(username,password)

import sys

print(sys.argv)